version: "3.8"

services:
  db:
    image: postgres:latest
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - ./:/app/
    ports:
      - "127.0.0.1:8000:8000"

    command: fastapi dev src/main.py --host 0.0.0.0

volumes:
  postgres_data:
