version: "3.8"
services:
  db:
    image: postgres:latest
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - ./:/app/
    ports:
      - "127.0.0.1:8000:8000"
    restart: always

    command: fastapi run src/main.py --host 0.0.0.0
  nginx:
    image: nginx:latest
    ports:
      - "80:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
